# Generated by Django 4.1.7 on 2023-03-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='bike_image',
            field=models.ImageField(blank=True, default='coming-soon2.jpg', null=True, upload_to='bike_images/'),
        ),
    ]
