# Generated by Django 4.1.7 on 2023-03-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_rename_style_trucks_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucks',
            name='truck_image',
            field=models.ImageField(blank=True, default='coming-soon2.jpg', null=True, upload_to='truck_images/'),
        ),
    ]
