# Generated by Django 4.1.7 on 2023-03-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_rename_truck_image_cars_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_image',
            field=models.ImageField(blank=True, default='coming-soon2.jpg', null=True, upload_to='car_images/'),
        ),
    ]
