# Generated by Django 4.1.7 on 2023-02-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_rename_truck_image_cars_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='mode_name',
            new_name='model_name',
        ),
    ]
