# Generated by Django 4.1.7 on 2023-03-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareParts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spareparts',
            old_name='truck_image',
            new_name='parts_image',
        ),
    ]
